// Code generated by command: go run asm_dense_dot_3.go -out dense_dot_3.s -stubs stub_dense_dot_3.go. DO NOT EDIT.

package toolbox

func denseDot3(n int, v0 []float32, v0Base int, v1 []float32, v1Base int, v2 []float32, v2Base int) float32
