// Code generated by command: go run asm_dense_dot_2.go -out dense_dot_2.s -stubs stub_dense_dot_2.go. DO NOT EDIT.

package toolbox

func denseDot2(n int, v0 []float32, v0Base int, v1 []float32, v1Base int) float32
