// Code generated by command: go run asm_dense_backprop_djdw_slice.go -out dense_backprop_djdw_slice.s -stubs stub_dense_backprop_djdw_slice.go. DO NOT EDIT.

package toolbox

func denseBackpropDjdwSliceKernel(batchSize int, inputSize int, djdaT []float32, dadzT []float32, xT []float32, djdw []float32, iStart int, jStart int, elementsToCompute int)
